jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'test/AvaloniaEdit.Tests'
    displayName: 'Run Tests'

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\build.ps1
      arguments: > # Use this to avoid newline characters in multiline string
        -Platform "AnyCPU"
        -Configuration "Release"
    displayName: 'Build and Package'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
      artifactName: 'Nuget'
    condition: succeeded()

