<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaloniaVersion>11.0.0</AvaloniaVersion>
    <AvaloniaSampleVersion>11.3.0</AvaloniaSampleVersion>
    <TextMateSharpVersion>1.0.66</TextMateSharpVersion>
    <VersionSuffix>beta</VersionSuffix>
  </PropertyGroup>
</Project>
